Pull request template added
TheAlgorithms/website pull request #88
Opened 2021-06-02 21:01 UTC by Kunal-2001

A pull request template for basic information

2021-06-02 21:19 UTC, Panquesito7 reviewed
👍 Good work.

2021-06-02 21:19 UTC, Panquesito7 commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] I ran `yarn build` to check if everything still builds successfully.
```suggestion
- [ ] I ran `yarn build` to check everything still builds successfully.
```

2021-06-02 22:18 UTC, Kunal-2001 commented
> 👍 Good work.

Thanks

2021-06-02 23:23 UTC, Panquesito7 approved these changes, later dismissed
LGTM. Thank you for your contribution! 👍 🎉

2021-06-03 15:21 UTC, maltejur requested changes

2021-06-03 15:21 UTC, maltejur commented on .github/PULL_REQUEST_TEMPLATE.md
> +
```suggestion
```

2021-06-03 15:21 UTC, maltejur commented on .github/PULL_REQUEST_TEMPLATE.md
> +
```suggestion
```

2021-06-03 15:21 UTC, maltejur commented on .github/PULL_REQUEST_TEMPLATE.md
> +
```suggestion
```

2021-06-03 15:21 UTC, maltejur commented on .github/PULL_REQUEST_TEMPLATE.md
> +Fixes #
```suggestion
Closes #
```

2021-06-03 15:21 UTC, maltejur commented on .github/PULL_REQUEST_TEMPLATE.md
> +<!-- This will automatically close the issue number mentioned when merged in main branch -->
```suggestion
<!-- Add the number of the issue this pull request is closing here -->
```

2021-06-03 17:31 UTC, maltejur approved these changes

2021-06-03 18:03 UTC, merged